/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    kotlin("jvm") version "1.7.20"
    kotlin("plugin.spring") version "1.7.20"
    id("com.netflix.dgs.codegen") version "5.6.0"
    id("org.springframework.boot") version "2.6.3"
}

group = "demo"
version = "0.0.1-SNAPSHOT"
description = "demo"
java.sourceCompatibility = JavaVersion.VERSION_1_8


repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation(platform("com.netflix.graphql.dgs:graphql-dgs-platform-dependencies:latest.release"))
    implementation("com.netflix.graphql.dgs:graphql-dgs-spring-boot-starter")
    implementation("com.netflix.graphql.dgs:graphql-dgs-extended-scalars")
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.jetbrains.kotlin:kotlin-reflect:1.7.20")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.20")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.7.5")
}


tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
